WARNING 2025-09-11 20:48:03,776 log Not Found: /@vite/client
WARNING 2025-09-11 20:48:03,981 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-11 20:48:30,019 log Not Found: /@vite/client
WARNING 2025-09-11 20:48:30,116 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-11 20:49:06,220 log Not Found: /@vite/client
WARNING 2025-09-11 20:49:06,228 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-12 13:32:51,227 log Not Found: /@vite/client
WARNING 2025-09-12 13:32:51,269 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-12 13:37:28,251 log Not Found: /@vite/client
WARNING 2025-09-12 13:37:28,327 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-12 13:37:46,766 log Not Found: /@vite/client
WARNING 2025-09-12 13:37:46,829 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-12 13:37:57,635 log Not Found: /@vite/client
WARNING 2025-09-12 13:37:57,657 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-12 13:38:19,634 log Not Found: /@vite/client
WARNING 2025-09-12 13:38:19,650 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 21:54:16,627 log Not Found: /@vite/client
WARNING 2025-09-15 21:54:16,770 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-15 21:54:26,529 log Internal Server Error: /admin-dashboard/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\users\views.py", line 168, in admin_dashboard
    response = render(request, 'users/admin_dashboard.html', context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'export_quotation_docx' not found. 'export_quotation_docx' is not a valid view function or pattern name.
ERROR 2025-09-15 21:54:26,864 basehttp "GET /admin-dashboard/ HTTP/1.1" 500 202542
WARNING 2025-09-15 21:54:29,098 log Not Found: /@vite/client
WARNING 2025-09-15 21:54:29,100 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-15 22:02:24,552 log Internal Server Error: /admin-dashboard/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\users\views.py", line 168, in admin_dashboard
    response = render(request, 'users/admin_dashboard.html', context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'export_invoice_docx' not found. 'export_invoice_docx' is not a valid view function or pattern name.
ERROR 2025-09-15 22:02:24,565 basehttp "GET /admin-dashboard/?ide_webview_request_time=1758016941039 HTTP/1.1" 500 202968
WARNING 2025-09-15 22:02:25,770 log Not Found: /@vite/client
WARNING 2025-09-15 22:02:25,906 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-15 22:03:36,752 log Internal Server Error: /admin-dashboard/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\users\views.py", line 168, in admin_dashboard
    response = render(request, 'users/admin_dashboard.html', context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'export_invoice_docx' not found. 'export_invoice_docx' is not a valid view function or pattern name.
ERROR 2025-09-15 22:03:36,762 basehttp "GET /admin-dashboard/?ide_webview_request_time=1758016941039 HTTP/1.1" 500 203233
WARNING 2025-09-15 22:03:37,725 log Not Found: /@vite/client
WARNING 2025-09-15 22:03:37,749 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-15 22:03:46,121 log Internal Server Error: /admin-dashboard/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\users\views.py", line 168, in admin_dashboard
    response = render(request, 'users/admin_dashboard.html', context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'export_invoice_docx' not found. 'export_invoice_docx' is not a valid view function or pattern name.
ERROR 2025-09-15 22:03:46,137 basehttp "GET /admin-dashboard/?ide_webview_request_time=1758016941039 HTTP/1.1" 500 203233
WARNING 2025-09-15 22:03:46,812 log Not Found: /@vite/client
WARNING 2025-09-15 22:03:46,819 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-15 22:04:03,928 log Internal Server Error: /admin-dashboard/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\users\views.py", line 168, in admin_dashboard
    response = render(request, 'users/admin_dashboard.html', context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'export_invoice_docx' not found. 'export_invoice_docx' is not a valid view function or pattern name.
ERROR 2025-09-15 22:04:04,008 basehttp "GET /admin-dashboard/ HTTP/1.1" 500 202228
WARNING 2025-09-15 22:04:04,724 log Not Found: /@vite/client
WARNING 2025-09-15 22:04:04,728 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:04:11,329 log Not Found: /@vite/client
WARNING 2025-09-15 22:04:11,329 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-15 22:04:16,702 log Internal Server Error: /admin-dashboard/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\users\views.py", line 168, in admin_dashboard
    response = render(request, 'users/admin_dashboard.html', context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'export_invoice_docx' not found. 'export_invoice_docx' is not a valid view function or pattern name.
ERROR 2025-09-15 22:04:17,267 basehttp "GET /admin-dashboard/ HTTP/1.1" 500 202359
WARNING 2025-09-15 22:04:17,956 log Not Found: /@vite/client
WARNING 2025-09-15 22:04:17,961 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-15 22:07:08,873 log Internal Server Error: /admin-dashboard/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\users\views.py", line 168, in admin_dashboard
    response = render(request, 'users/admin_dashboard.html', context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'export_invoice_docx' not found. 'export_invoice_docx' is not a valid view function or pattern name.
ERROR 2025-09-15 22:07:08,952 basehttp "GET /admin-dashboard/ HTTP/1.1" 500 202624
WARNING 2025-09-15 22:07:09,571 log Not Found: /@vite/client
WARNING 2025-09-15 22:07:09,582 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-15 22:07:11,807 log Internal Server Error: /admin-dashboard/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\users\views.py", line 168, in admin_dashboard
    response = render(request, 'users/admin_dashboard.html', context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'export_invoice_docx' not found. 'export_invoice_docx' is not a valid view function or pattern name.
ERROR 2025-09-15 22:07:11,824 basehttp "GET /admin-dashboard/ HTTP/1.1" 500 202624
WARNING 2025-09-15 22:07:12,451 log Not Found: /@vite/client
WARNING 2025-09-15 22:07:12,456 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:07:56,213 log Not Found: /@vite/client
WARNING 2025-09-15 22:07:56,236 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-15 22:08:01,767 log Internal Server Error: /admin-dashboard/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\users\views.py", line 168, in admin_dashboard
    response = render(request, 'users/admin_dashboard.html', context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'export_invoice_docx' not found. 'export_invoice_docx' is not a valid view function or pattern name.
ERROR 2025-09-15 22:08:01,808 basehttp "GET /admin-dashboard/ HTTP/1.1" 500 202359
WARNING 2025-09-15 22:08:03,047 log Not Found: /@vite/client
WARNING 2025-09-15 22:08:03,053 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-15 22:09:56,739 log Internal Server Error: /admin-dashboard/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\users\views.py", line 168, in admin_dashboard
    response = render(request, 'users/admin_dashboard.html', context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'export_invoice_docx' not found. 'export_invoice_docx' is not a valid view function or pattern name.
ERROR 2025-09-15 22:09:56,756 basehttp "GET /admin-dashboard/ HTTP/1.1" 500 202624
WARNING 2025-09-15 22:09:57,440 log Not Found: /@vite/client
WARNING 2025-09-15 22:09:57,450 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:10:03,105 log Not Found: /@vite/client
WARNING 2025-09-15 22:10:03,727 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:11:45,275 log Not Found: /@vite/client
WARNING 2025-09-15 22:11:45,313 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-15 22:12:08,082 log Internal Server Error: /admin-dashboard/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\users\views.py", line 168, in admin_dashboard
    response = render(request, 'users/admin_dashboard.html', context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'export_invoice_docx' not found. 'export_invoice_docx' is not a valid view function or pattern name.
ERROR 2025-09-15 22:12:08,283 basehttp "GET /admin-dashboard/ HTTP/1.1" 500 202812
WARNING 2025-09-15 22:12:09,102 log Not Found: /@vite/client
WARNING 2025-09-15 22:12:09,122 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:21:43,393 log Not Found: /@vite/client
WARNING 2025-09-15 22:21:43,398 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:22:20,023 log Not Found: /@vite/client
WARNING 2025-09-15 22:22:20,116 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:23:19,711 log Not Found: /@vite/client
WARNING 2025-09-15 22:23:19,836 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:23:58,586 log Not Found: /@vite/client
WARNING 2025-09-15 22:23:58,705 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:24:30,822 log Not Found: /@vite/client
WARNING 2025-09-15 22:24:30,822 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:24:57,134 log Not Found: /@vite/client
WARNING 2025-09-15 22:24:57,166 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-15 22:25:03,851 log Internal Server Error: /invoices/3/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\views.py", line 221, in export_invoice_docx
    from .docx_utils import generate_invoice_docx
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 5, in <module>
    from docx import Document
ModuleNotFoundError: No module named 'docx'
ERROR 2025-09-15 22:25:03,868 basehttp "GET /invoices/3/docx/ HTTP/1.1" 500 87021
WARNING 2025-09-15 22:25:05,183 log Not Found: /@vite/client
WARNING 2025-09-15 22:25:05,186 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:25:16,275 log Not Found: /@vite/client
WARNING 2025-09-15 22:25:16,375 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:25:26,200 log Not Found: /@vite/client
WARNING 2025-09-15 22:25:26,208 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:35:03,084 log Not Found: /@vite/client
WARNING 2025-09-15 22:35:03,257 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-15 22:35:07,471 log Internal Server Error: /invoices/13/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\views.py", line 221, in export_invoice_docx
    from .docx_utils import generate_invoice_docx
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 5, in <module>
    from docx import Document
ModuleNotFoundError: No module named 'docx'
ERROR 2025-09-15 22:35:07,476 basehttp "GET /invoices/13/docx/ HTTP/1.1" 500 87028
WARNING 2025-09-15 22:35:07,912 log Not Found: /@vite/client
WARNING 2025-09-15 22:35:07,916 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:38:02,329 log Not Found: /@vite/client
WARNING 2025-09-15 22:38:02,521 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:38:08,970 log Not Found: /@vite/client
WARNING 2025-09-15 22:38:09,042 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:38:20,744 log Not Found: /@vite/client
WARNING 2025-09-15 22:38:20,766 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-15 22:38:28,625 log Internal Server Error: /quotations/7/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\quotations\views.py", line 156, in quotation_docx
    from invoices.docx_utils import generate_quotation_docx
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 5, in <module>
    from docx import Document
ModuleNotFoundError: No module named 'docx'
ERROR 2025-09-15 22:38:28,658 basehttp "GET /quotations/7/docx/ HTTP/1.1" 500 87063
ERROR 2025-09-15 22:38:30,183 log Internal Server Error: /quotations/7/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\quotations\views.py", line 156, in quotation_docx
    from invoices.docx_utils import generate_quotation_docx
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 5, in <module>
    from docx import Document
ModuleNotFoundError: No module named 'docx'
ERROR 2025-09-15 22:38:30,201 basehttp "GET /quotations/7/docx/ HTTP/1.1" 500 86932
WARNING 2025-09-15 22:38:30,356 log Not Found: /@vite/client
WARNING 2025-09-15 22:38:30,457 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:38:38,772 log Not Found: /@vite/client
WARNING 2025-09-15 22:38:38,780 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:38:41,743 log Not Found: /@vite/client
WARNING 2025-09-15 22:38:41,765 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:45:50,722 log Not Found: /@vite/client
WARNING 2025-09-15 22:45:50,811 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:46:04,266 log Not Found: /@vite/client
WARNING 2025-09-15 22:46:04,310 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:46:38,794 log Not Found: /@vite/client
WARNING 2025-09-15 22:46:39,065 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-15 22:46:45,084 log Internal Server Error: /invoices/13/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\views.py", line 221, in export_invoice_docx
    from .docx_utils import generate_invoice_docx
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 5, in <module>
    from docx import Document
ModuleNotFoundError: No module named 'docx'
ERROR 2025-09-15 22:46:45,096 basehttp "GET /invoices/13/docx/ HTTP/1.1" 500 87021
ERROR 2025-09-15 22:46:45,487 log Internal Server Error: /invoices/13/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\views.py", line 221, in export_invoice_docx
    from .docx_utils import generate_invoice_docx
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 5, in <module>
    from docx import Document
ModuleNotFoundError: No module named 'docx'
ERROR 2025-09-15 22:46:45,494 basehttp "GET /invoices/13/docx/ HTTP/1.1" 500 86890
WARNING 2025-09-15 22:46:45,681 log Not Found: /@vite/client
WARNING 2025-09-15 22:46:45,684 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 22:46:52,511 log Not Found: /@vite/client
WARNING 2025-09-15 22:46:52,518 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 23:21:19,606 log Not Found: /@vite/client
WARNING 2025-09-15 23:21:19,962 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 23:21:23,116 log Not Found: /@vite/client
WARNING 2025-09-15 23:21:23,294 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 23:22:37,305 log Not Found: /@vite/client
WARNING 2025-09-15 23:22:37,331 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-15 23:22:40,779 log Not Found: /@vite/client
WARNING 2025-09-15 23:22:40,782 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 00:13:19,642 log Not Found: /@vite/client
WARNING 2025-09-16 00:13:19,659 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 00:13:57,470 log Not Found: /@vite/client
WARNING 2025-09-16 00:13:57,604 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-16 00:14:21,420 log Internal Server Error: /invoices/13/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\views.py", line 224, in export_invoice_docx
    from .docx_utils import generate_invoice_docx
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 5, in <module>
    from docx import Document
ModuleNotFoundError: No module named 'docx'
ERROR 2025-09-16 00:14:21,470 basehttp "GET /invoices/13/docx/ HTTP/1.1" 500 87021
ERROR 2025-09-16 00:14:21,677 log Internal Server Error: /invoices/13/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\views.py", line 224, in export_invoice_docx
    from .docx_utils import generate_invoice_docx
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 5, in <module>
    from docx import Document
ModuleNotFoundError: No module named 'docx'
ERROR 2025-09-16 00:14:21,683 basehttp "GET /invoices/13/docx/ HTTP/1.1" 500 86890
WARNING 2025-09-16 00:14:23,528 log Not Found: /@vite/client
WARNING 2025-09-16 00:14:23,631 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 00:14:55,530 log Not Found: /@vite/client
WARNING 2025-09-16 00:14:55,535 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 00:15:04,851 log Not Found: /@vite/client
WARNING 2025-09-16 00:15:04,851 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 00:36:28,600 log Not Found: /@vite/client
WARNING 2025-09-16 00:36:28,754 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-16 00:36:34,881 log Internal Server Error: /invoices/12/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\views.py", line 224, in export_invoice_docx
    from .docx_utils import generate_invoice_docx
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 5, in <module>
    from docx import Document
ModuleNotFoundError: No module named 'docx'
ERROR 2025-09-16 00:36:34,908 basehttp "GET /invoices/12/docx/ HTTP/1.1" 500 87041
ERROR 2025-09-16 00:36:35,515 log Internal Server Error: /invoices/12/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\views.py", line 224, in export_invoice_docx
    from .docx_utils import generate_invoice_docx
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 5, in <module>
    from docx import Document
ModuleNotFoundError: No module named 'docx'
ERROR 2025-09-16 00:36:35,537 basehttp "GET /invoices/12/docx/ HTTP/1.1" 500 86910
WARNING 2025-09-16 00:36:36,073 log Not Found: /@vite/client
WARNING 2025-09-16 00:36:36,092 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 00:37:05,801 log Not Found: /@vite/client
WARNING 2025-09-16 00:37:05,816 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 00:37:10,602 log Not Found: /@vite/client
WARNING 2025-09-16 00:37:10,744 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 01:08:32,758 log Not Found: /@vite/client
WARNING 2025-09-16 01:08:32,791 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-16 01:08:45,540 log Internal Server Error: /invoices/13/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\views.py", line 225, in export_invoice_docx
    return generate_invoice_docx(invoice)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 99, in generate_invoice_docx
    document.add_paragraph(f"Date: {invoice.date.strftime('%d-%m-%Y')}")
AttributeError: 'Invoice' object has no attribute 'date'
ERROR 2025-09-16 01:08:45,658 basehttp "GET /invoices/13/docx/ HTTP/1.1" 500 80849
ERROR 2025-09-16 01:08:46,405 log Internal Server Error: /invoices/13/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\views.py", line 225, in export_invoice_docx
    return generate_invoice_docx(invoice)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 99, in generate_invoice_docx
    document.add_paragraph(f"Date: {invoice.date.strftime('%d-%m-%Y')}")
AttributeError: 'Invoice' object has no attribute 'date'
ERROR 2025-09-16 01:08:46,451 basehttp "GET /invoices/13/docx/ HTTP/1.1" 500 80718
WARNING 2025-09-16 01:08:46,717 log Not Found: /@vite/client
WARNING 2025-09-16 01:08:46,721 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 01:09:14,086 log Not Found: /@vite/client
WARNING 2025-09-16 01:09:14,191 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 01:09:27,269 log Not Found: /@vite/client
WARNING 2025-09-16 01:09:27,438 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-16 01:09:34,397 log Internal Server Error: /quotations/7/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\quotations\views.py", line 163, in quotation_docx
    return generate_quotation_docx(quotation)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 236, in generate_quotation_docx
    document.add_paragraph(f"Date: {quotation.date.strftime('%d-%m-%Y')}")
AttributeError: 'Quotation' object has no attribute 'date'
ERROR 2025-09-16 01:09:34,550 basehttp "GET /quotations/7/docx/ HTTP/1.1" 500 80942
ERROR 2025-09-16 01:09:35,399 log Internal Server Error: /quotations/7/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\quotations\views.py", line 163, in quotation_docx
    return generate_quotation_docx(quotation)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 236, in generate_quotation_docx
    document.add_paragraph(f"Date: {quotation.date.strftime('%d-%m-%Y')}")
AttributeError: 'Quotation' object has no attribute 'date'
WARNING 2025-09-16 01:09:35,433 log Not Found: /@vite/client
WARNING 2025-09-16 01:09:35,438 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-16 01:09:35,439 basehttp "GET /quotations/7/docx/ HTTP/1.1" 500 80811
WARNING 2025-09-16 01:10:17,709 log Not Found: /@vite/client
WARNING 2025-09-16 01:10:17,715 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 01:10:26,801 log Not Found: /@vite/client
WARNING 2025-09-16 01:10:26,870 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 01:11:00,862 log Not Found: /@vite/client
WARNING 2025-09-16 01:11:00,911 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 01:11:04,310 log Not Found: /@vite/client
WARNING 2025-09-16 01:11:04,321 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 01:11:14,336 log Not Found: /@vite/client
WARNING 2025-09-16 01:11:14,361 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 01:11:37,334 log Not Found: /@vite/client
WARNING 2025-09-16 01:11:37,334 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 01:11:43,894 log Not Found: /@vite/client
WARNING 2025-09-16 01:11:44,010 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 01:15:47,834 log Not Found: /@vite/client
WARNING 2025-09-16 01:15:47,842 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 01:16:33,201 log Not Found: /@vite/client
WARNING 2025-09-16 01:16:33,223 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-16 01:16:55,721 log Internal Server Error: /quotations/8/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\quotations\views.py", line 163, in quotation_docx
    return generate_quotation_docx(quotation)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 236, in generate_quotation_docx
    document.add_paragraph(f"Date: {quotation.date.strftime('%d-%m-%Y')}")
AttributeError: 'Quotation' object has no attribute 'date'
ERROR 2025-09-16 01:16:55,737 basehttp "GET /quotations/8/docx/ HTTP/1.1" 500 80942
WARNING 2025-09-16 01:16:56,993 log Not Found: /@vite/client
WARNING 2025-09-16 01:16:57,037 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-16 01:16:57,031 log Internal Server Error: /quotations/8/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\quotations\views.py", line 163, in quotation_docx
    return generate_quotation_docx(quotation)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 236, in generate_quotation_docx
    document.add_paragraph(f"Date: {quotation.date.strftime('%d-%m-%Y')}")
AttributeError: 'Quotation' object has no attribute 'date'
ERROR 2025-09-16 01:16:57,149 basehttp "GET /quotations/8/docx/ HTTP/1.1" 500 80811
WARNING 2025-09-16 02:09:46,230 log Not Found: /@vite/client
WARNING 2025-09-16 02:09:46,289 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-16 02:10:07,466 log Internal Server Error: /quotations/7/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\quotations\views.py", line 163, in quotation_docx
    return generate_quotation_docx(quotation)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 289, in generate_quotation_docx
    vat_cells[1].text = f"{quotation.currency} {'{:,.0f}'.format(quotation.vat)}"
AttributeError: 'Quotation' object has no attribute 'vat'
ERROR 2025-09-16 02:10:07,612 basehttp "GET /quotations/7/docx/ HTTP/1.1" 500 84221
ERROR 2025-09-16 02:10:08,124 log Internal Server Error: /quotations/7/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\quotations\views.py", line 163, in quotation_docx
    return generate_quotation_docx(quotation)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 289, in generate_quotation_docx
    vat_cells[1].text = f"{quotation.currency} {'{:,.0f}'.format(quotation.vat)}"
AttributeError: 'Quotation' object has no attribute 'vat'
ERROR 2025-09-16 02:10:08,235 basehttp "GET /quotations/7/docx/ HTTP/1.1" 500 84090
WARNING 2025-09-16 02:10:08,843 log Not Found: /@vite/client
WARNING 2025-09-16 02:10:08,846 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 02:10:50,618 log Not Found: /@vite/client
WARNING 2025-09-16 02:10:50,658 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 02:11:12,671 log Not Found: /@vite/client
WARNING 2025-09-16 02:11:12,777 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 08:28:12,555 log Not Found: /@vite/client
WARNING 2025-09-16 08:28:12,587 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 08:29:05,158 log Not Found: /@vite/client
WARNING 2025-09-16 08:29:05,161 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 08:29:33,736 log Not Found: /@vite/client
WARNING 2025-09-16 08:29:33,851 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-16 08:29:45,882 log Internal Server Error: /quotations/8/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\quotations\views.py", line 163, in quotation_docx
    return generate_quotation_docx(quotation)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 289, in generate_quotation_docx
    vat_cells[1].text = f"{quotation.currency} {'{:,.0f}'.format(quotation.vat)}"
AttributeError: 'Quotation' object has no attribute 'vat'
ERROR 2025-09-16 08:29:46,065 basehttp "GET /quotations/8/docx/ HTTP/1.1" 500 84234
ERROR 2025-09-16 08:29:46,751 log Internal Server Error: /quotations/8/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\quotations\views.py", line 163, in quotation_docx
    return generate_quotation_docx(quotation)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 289, in generate_quotation_docx
    vat_cells[1].text = f"{quotation.currency} {'{:,.0f}'.format(quotation.vat)}"
AttributeError: 'Quotation' object has no attribute 'vat'
ERROR 2025-09-16 08:29:46,780 basehttp "GET /quotations/8/docx/ HTTP/1.1" 500 84103
WARNING 2025-09-16 08:29:48,974 log Not Found: /@vite/client
WARNING 2025-09-16 08:29:48,986 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 08:33:38,443 log Not Found: /@vite/client
WARNING 2025-09-16 08:33:38,457 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 08:33:48,931 log Not Found: /@vite/client
WARNING 2025-09-16 08:33:48,976 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-16 08:33:58,440 log Internal Server Error: /invoices/12/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\views.py", line 225, in export_invoice_docx
    return generate_invoice_docx(invoice)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 99, in generate_invoice_docx
    document.add_paragraph(f"Date: {invoice.date.strftime('%d-%m-%Y')}")
AttributeError: 'Invoice' object has no attribute 'date'
ERROR 2025-09-16 08:33:58,463 basehttp "GET /invoices/12/docx/ HTTP/1.1" 500 80889
ERROR 2025-09-16 08:33:58,968 log Internal Server Error: /invoices/12/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\views.py", line 225, in export_invoice_docx
    return generate_invoice_docx(invoice)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 99, in generate_invoice_docx
    document.add_paragraph(f"Date: {invoice.date.strftime('%d-%m-%Y')}")
AttributeError: 'Invoice' object has no attribute 'date'
ERROR 2025-09-16 08:33:58,974 basehttp "GET /invoices/12/docx/ HTTP/1.1" 500 80758
WARNING 2025-09-16 08:33:59,238 log Not Found: /@vite/client
WARNING 2025-09-16 08:33:59,298 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 08:35:58,039 log Not Found: /@vite/client
WARNING 2025-09-16 08:35:58,039 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 08:52:40,212 log Not Found: /@vite/client
WARNING 2025-09-16 08:52:40,273 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 08:53:22,795 log Not Found: /@vite/client
WARNING 2025-09-16 08:53:23,016 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 08:59:36,992 log Not Found: /@vite/client
WARNING 2025-09-16 08:59:37,008 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 08:59:40,128 log Not Found: /@vite/client
WARNING 2025-09-16 08:59:40,198 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 08:59:47,757 log Not Found: /@vite/client
WARNING 2025-09-16 08:59:47,877 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 09:10:04,204 log Not Found: /@vite/client
WARNING 2025-09-16 09:10:04,220 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 09:10:58,779 log Not Found: /@vite/client
WARNING 2025-09-16 09:10:58,783 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 09:11:30,530 log Not Found: /@vite/client
WARNING 2025-09-16 09:11:30,530 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 09:11:35,799 log Not Found: /@vite/client
WARNING 2025-09-16 09:11:35,820 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 09:11:39,670 log Not Found: /@vite/client
WARNING 2025-09-16 09:11:39,696 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 09:13:07,526 log Not Found: /@vite/client
WARNING 2025-09-16 09:13:07,637 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 09:13:16,130 log Not Found: /@vite/client
WARNING 2025-09-16 09:13:16,260 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-16 09:31:33,916 log Internal Server Error: /invoices/12/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\views.py", line 225, in export_invoice_docx
    return generate_invoice_docx(invoice)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 99, in generate_invoice_docx
    document.add_paragraph(f"Date: {invoice.date.strftime('%d-%m-%Y')}")
AttributeError: 'Invoice' object has no attribute 'date'
ERROR 2025-09-16 09:31:33,963 basehttp "GET /invoices/12/docx/ HTTP/1.1" 500 80896
WARNING 2025-09-16 09:31:35,140 log Not Found: /@vite/client
WARNING 2025-09-16 09:31:35,142 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 09:39:29,736 log Not Found: /@vite/client
WARNING 2025-09-16 09:39:29,883 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 09:39:44,570 log Not Found: /@vite/client
WARNING 2025-09-16 09:39:44,799 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 09:41:06,764 log Not Found: /@vite/client
WARNING 2025-09-16 09:41:06,872 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 09:41:13,304 log Not Found: /@vite/client
WARNING 2025-09-16 09:41:13,336 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 09:41:24,164 log Not Found: /@vite/client
WARNING 2025-09-16 09:41:24,271 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 09:41:28,669 log Not Found: /@vite/client
WARNING 2025-09-16 09:41:28,684 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 09:41:37,906 log Not Found: /@vite/client
WARNING 2025-09-16 09:41:37,954 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 09:42:48,507 log Not Found: /@vite/client
WARNING 2025-09-16 09:42:48,613 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 09:43:33,250 log Not Found: /@vite/client
WARNING 2025-09-16 09:43:33,263 basehttp "GET /@vite/client HTTP/1.1" 404 5857
ERROR 2025-09-16 09:59:11,332 log Internal Server Error: /invoices/13/docx/
Traceback (most recent call last):
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\KADI-LIFE\AppData\Roaming\Python\Python310\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\views.py", line 225, in export_invoice_docx
    return generate_invoice_docx(invoice)
  File "C:\Users\KADI-LIFE\Desktop\Invoice_App\invoices\docx_utils.py", line 99, in generate_invoice_docx
    document.add_paragraph(f"Date: {invoice.date.strftime('%d-%m-%Y')}")
AttributeError: 'Invoice' object has no attribute 'date'
ERROR 2025-09-16 09:59:11,346 basehttp "GET /invoices/13/docx/ HTTP/1.1" 500 80856
WARNING 2025-09-16 09:59:12,070 log Not Found: /@vite/client
WARNING 2025-09-16 09:59:12,196 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 10:14:11,208 log Not Found: /@vite/client
WARNING 2025-09-16 10:14:11,319 basehttp "GET /@vite/client HTTP/1.1" 404 5857
WARNING 2025-09-16 10:34:35,741 log Not Found: /@vite/client
WARNING 2025-09-16 10:34:35,803 basehttp "GET /@vite/client HTTP/1.1" 404 5857
